const SEED=[{market:'TW',symbol:'2330',name:'台積電',kind:'hold',shares:100,cost:980,note:'核心持股'},{market:'US',symbol:'NVDA',name:'NVIDIA',kind:'watch',shares:0,cost:0,note:'等回檔'},{market:'US',symbol:'AAPL',name:'Apple',kind:'hold',shares:10,cost:190,note:''}];
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items;try{items=JSON.parse(localStorage.getItem('desk-items')||'null')||structuredClone(SEED)}catch{items=structuredClone(SEED)}
let selected=0,deferredPrompt=null,renderId=0;const quoteCache={};
function yahooSymbol(item){const symbol=item.symbol.toUpperCase();return item.market==='TW'?symbol+'.TW':symbol}
async function getJSON(url){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);try{const res=await fetch(url,{signal:controller.signal,cache:'no-store'});if(!res.ok)throw Error('HTTP '+res.status);return await res.json()}finally{clearTimeout(timeout)}}
function parseChart(data){const result=data.chart?.result?.[0];if(!result)throw Error(data.chart?.error?.description||'沒有行情資料');const session=result.meta?.currentTradingPeriod?.regular;const rows=(result.timestamp||[]).map((t,i)=>({t,p:result.indicators?.quote?.[0]?.close?.[i]})).filter(row=>Number.isFinite(row.p)&&row.p>0&&!(session&&Date.now()<session.end*1000&&row.t>=session.start));if(rows.length<60)throw Error('日K不足60筆');return {prices:rows.slice(-120).map(row=>row.p),asOf:new Date(rows.at(-1).t*1000).toISOString().slice(0,10),source:'Yahoo 日K',currency:result.meta?.currency||''}}
async function fetchDaily(item,force=false){const key=item.market+':'+item.symbol.toUpperCase();if(!force&&quoteCache[key]&&Date.now()-quoteCache[key].fetchedAt<15*60*1000)return quoteCache[key];let snapshot=null;try{const data=await getJSON('./data/quotes.json?t='+Date.now());const q=data.quotes?.[key];if(q&&q.prices?.length>=60&&q.prices.every(p=>Number.isFinite(p)&&p>0))snapshot={...q,source:'每日排程 · Yahoo 日K'};if(snapshot&&Date.now()-Date.parse(snapshot.asOf)<4*86400000){quoteCache[key]={...snapshot,fetchedAt:Date.now()};return quoteCache[key]}}catch{}
const symbols=item.market==='TW'?[yahooSymbol(item),item.symbol.toUpperCase()+'.TWO']:[yahooSymbol(item)];const errors=[];for(const symbol of symbols){const yahoo='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?interval=1d&range=6mo';for(const url of [yahoo,'https://api.allorigins.win/raw?url='+encodeURIComponent(yahoo)]){try{const quote=parseChart(await getJSON(url));quoteCache[key]={...quote,fetchedAt:Date.now()};return quoteCache[key]}catch(err){errors.push(err.message)}}}
if(snapshot)return {...snapshot,stale:true,warning:'最新行情取得失敗，保留歷史資料'};throw Error('行情來源無法連線、受到限流，或代號無資料。請稍後重試。');}
function save(){localStorage.setItem('desk-items',JSON.stringify(items))}
const num=(n,d=2)=>Number(n).toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d});
const signed=n=>(n>0?'+':'')+num(n)+'%';
function draw(a){
const p=a.prices,w=720,h=300,left=78,right=18,top=18,bottom=38;
const line=n=>p.map((_,i)=>i+1<n?null:StockIndicators.sma(p.slice(0,i+1),n));const m20=line(20),m60=line(60);
const all=[...p,...m20.filter(v=>v!==null),...m60.filter(v=>v!==null),a.support,a.resistance];let min=Math.min(...all),max=Math.max(...all);const buffer=(max-min)*.08||1;min-=buffer;max+=buffer;
const x=i=>left+i/(p.length-1)*(w-left-right),y=v=>h-bottom-(v-min)/(max-min)*(h-top-bottom);
const path=(arr,color)=>`<polyline fill="none" stroke="${color}" stroke-width="2" points="${arr.map((v,i)=>v===null?'':x(i)+','+y(v)).filter(Boolean).join(' ')}"/>`;
const grid=Array.from({length:4},(_,i)=>{const v=min+(max-min)*i/3;return `<line x1="${left}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}" stroke="#2a3642"/><text x="${left-8}" y="${y(v)+4}" text-anchor="end" fill="#b4c3cf" font-size="16">${num(v,1)}</text>`}).join('');
const level=(v,color)=>`<line x1="${left}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}" stroke="${color}" stroke-dasharray="5 5" opacity=".7"/>`;
return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="最近${p.length}筆收盤價與20、60日均線">${grid}${level(a.support,'#e07a7a')}${level(a.resistance,'#b39ee8')}${path(m60,'#e0c07a')}${path(m20,'#7cacdf')}${path(p,'#8fd0a8')}<text x="${left}" y="${h-12}" fill="#b4c3cf" font-size="16">最近${p.length}筆收盤 →</text><text x="${w-right}" y="${h-12}" text-anchor="end" fill="#b4c3cf" font-size="16">最新</text></svg><p class="chart-key"><span class="price">收盤</span><span class="ma20">20日均線</span><span class="ma60">60日均線</span><span>虛線：前20日收盤範圍</span></p>`;
}
function researchHTML(item,quote,a){
const currency=quote.currency||(item.market==='TW'?'TWD':'USD');
const metric=(label,value,desc='')=>`<div class="metric"><span>${label}</span><strong>${value}</strong>${desc?`<small>${desc}</small>`:''}</div>`;
return `<article class="panel card"><div class="detail-top"><div><h2>${escapeHTML(item.market)} ${escapeHTML(item.symbol)} ${escapeHTML(item.name||'')}</h2><p class="note">${escapeHTML(quote.source)} · 資料截至 ${escapeHTML(quote.asOf||'日期不明')} · ${currency}</p></div><button id="refresh" class="ghost">更新資料</button></div>
${quote.stale?'<p class="error">'+escapeHTML(quote.warning)+'；以下為歷史狀態。</p>':''}
<div class="research-summary ${a.bias}"><span class="eyebrow">價格研究摘要 · 規則解讀</span><p>${a.summary}</p></div>
<div class="metrics">${metric('收盤',num(a.last),`單日 ${signed(a.change)}`)}${metric('20日均線乖離',signed(a.deviation),'價格距20日均線的差距')}${metric('RSI（14）',num(a.rsi,1),'Wilder平滑，範圍0–100')}${metric('MACD柱狀值',num(a.macd.hist),'12 / 26 / 9')}</div>
${draw(a)}
<section class="research-section"><h3>① 趨勢與動能</h3><p>${a.trendText}</p><p>20日均線相較5個交易日前 ${signed(a.slope20)}。${a.slope20>0?'均線仍向上。':a.slope20<0?'均線仍向下。':'均線持平。'}</p><p>${a.momentumText}</p><div class="returns">${a.returns.map(r=>`<span>近${r.n}日：<b>${r.value===null?'資料不足':signed(r.value)}</b></span>`).join('')}</div></section>
<section class="research-section"><h3>② 價格位置與波動</h3><div class="metrics">${metric('區間下緣',num(a.support),'前20日最低收盤')}${metric('區間上緣',num(a.resistance),'前20日最高收盤')}${metric('20日年化波動',num(a.volatility)+'%','近期日報酬波動 × √252')}${metric('近60日最大回落',signed(a.drawdown),'區間內高點至後續低點')}</div><p>${a.breakout?'已超過前20日收盤上緣，形成價格突破。':a.breakdown?'已跌破前20日收盤下緣，形成價格破位。':'仍在前20日收盤範圍內。'}這些價位是支撐／壓力的初步參考，沒有驗證多次觸碰。</p><p>布林通道（20日、±2倍標準差）：${num(a.lower)}–${num(a.upper)}，帶寬 ${num(a.bandWidth)}%。目前${a.last>a.upper?'在上軌之外，偏強且波動較大':a.last<a.lower?'在下軌之外，偏弱且波動較大':'在通道內'}；通道不是未來價格的保證範圍。</p></section>
<section class="research-section focus"><h3>③ 接下來追蹤什麼</h3><p>${a.monitor}</p><p>訊號${(a.bias==='bull'&&a.macd.hist<0)||(a.bias==='bear'&&a.macd.hist>0)?'出現分歧，先確認趨勢與動能能否重新同向。':'需由後續收盤確認，單日變動不代表趨勢已定。'}</p></section>
${item.kind==='hold'?`<section class="research-section"><h3>④ 持股狀態</h3>${a.holding?`<div class="metrics">${metric('持股市值',num(a.holding.value)+' '+currency)}${metric('帳面損益',num(a.holding.pnl)+' '+currency)}${metric('成本報酬',signed(a.holding.return))}</div><p class="note">按輸入股數與每股成本估算，未含手續費、稅、股息、匯率與公司行動。</p>`:'<p>輸入股數及每股成本後，可計算持股市值與帳面損益。</p>'}</section>`:''}
<section class="research-section"><h3>分析範圍</h3><p class="note">目前使用${a.prices.length}筆收盤價，尚未分析成交量、盤中高低價、財報、估值與新聞。突破未經量能確認；未做拆股與除權息調整的序列可能影響指標。這是程式規則解讀，沒有AI預測或勝率。</p><details><summary>指標怎麼算？</summary><p class="note">均線：最近N筆收盤的算術平均。RSI：14期Wilder平滑平均漲跌。MACD：EMA12−EMA26，訊號線為9期EMA，柱狀值為兩線之差。布林通道：20日均線±2倍母體標準差。區間參考排除當日，避免把當日新高誤當原有壓力。</p><a href="https://www.fidelity.com/learning-center/trading-investing/technical-analysis" target="_blank" rel="noopener">技術指標說明來源：Fidelity</a></details></section>
<p class="note">${escapeHTML(item.note||'尚未記錄投資假設')} · 股數 ${num(Number(item.shares)||0,0)} · 每股成本 ${num(Number(item.cost)||0)} · 研究輔助，不是投資建議。</p></article>`;
}
function renderList(){$('list').innerHTML=items.map((item,i)=>`<button class="item ${i===selected?'active':''}" data-i="${i}"><span>${item.market} ${escapeHTML(item.symbol)}<br><span class="tag">${item.kind==='hold'?'持股':'觀察'} · ${escapeHTML(item.name||'')}</span></span><span class="tag">移除</span></button>`).join('');$('list').querySelectorAll('.item').forEach(btn=>{btn.onclick=e=>{const i=Number(btn.dataset.i);if(e.target.classList.contains('tag')&&e.target.textContent==='移除'){items.splice(i,1);selected=0;save();render();return}selected=i;render()}})}
async function render(force=false){const requestId=++renderId;renderList();const item=items[selected];if(!item){$('detail').innerHTML="<div class='panel'>清單是空的。</div>";return}$('detail').innerHTML=`<article class='panel card'><h2>${item.market} ${escapeHTML(item.symbol)}</h2><p class='note'>正在抓公開日K…</p></article>`;let quote;try{quote=await fetchDaily(item,force)}catch(err){if(requestId!==renderId)return;$('detail').innerHTML=`<article class='panel card'><h2>${escapeHTML(item.symbol)}</h2><p class='error'>尚未取得真實行情，暫停技術分析。</p><p>${escapeHTML(err.message)}</p><button id='retry'>重新取得資料</button><p class='note'>排程資料目前涵蓋預設與常用標的；其他代號會嘗試公開行情來源。</p></article>`;$('retry').onclick=()=>render(true);return}if(requestId!==renderId)return;const a=StockIndicators.analyze(item,quote);$('detail').innerHTML=researchHTML(item,quote,a);$('refresh').onclick=()=>render(true)}
$('add').onclick=()=>{const symbol=$('symbol').value.trim().toUpperCase();if(!/^[A-Z0-9.^=-]{1,16}$/.test(symbol)){alert('請輸入有效股票代號，例如 2330 或 AAPL');return;}items.unshift({market:$('market').value,symbol,name:'',kind:$('kind').value,shares:Number($('shares').value||0),cost:Number($('cost').value||0),note:$('note').value.trim()});selected=0;save();render()};
$('reset').onclick=()=>{items=structuredClone(SEED);selected=0;save();render()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install').hidden=false});
$('install').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('install').hidden=true};
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();

setInterval(()=>{if(!document.hidden)render(true)},15*60*1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});
