const SEED=[{market:'TW',symbol:'2330',name:'台積電',kind:'hold',shares:100,cost:980,note:'核心持股'},{market:'US',symbol:'NVDA',name:'NVIDIA',kind:'watch',shares:0,cost:0,note:'等回檔'},{market:'US',symbol:'AAPL',name:'Apple',kind:'hold',shares:10,cost:190,note:''}];
function series(seed,drift){const out=[];let p=seed;for(let i=0;i<80;i++){p=Math.max(1,p+Math.sin(i/7)*drift*0.4+((i*17)%7-3)*drift*0.08);out.push(Math.round(p*100)/100)}return out}
const $=id=>document.getElementById(id);
let items=JSON.parse(localStorage.getItem('desk-items')||'null')||SEED;let selected=0;let deferredPrompt=null;const quoteCache={};
function yahooSymbol(item){const symbol=item.symbol.toUpperCase();return item.market==='TW'?symbol+'.TW':symbol}
async function fetchDaily(item){const key=item.market+':'+item.symbol.toUpperCase();if(quoteCache[key])return quoteCache[key];const yahoo='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(yahooSymbol(item))+'?interval=1d&range=6mo';const urls=[yahoo,'https://api.allorigins.win/raw?url='+encodeURIComponent(yahoo)];for(const url of urls){try{const res=await fetch(url);if(!res.ok)continue;const data=await res.json();const result=data.chart.results[0];const closes=result.indicators.quote[0].close.filter(n=>Number.isFinite(n));const stamps=result.timestamp||[];const lastStamp=stamps[stamps.length-1];if(closes.length<60)continue;quoteCache[key]={prices:closes.slice(-80),asOf:lastStamp?new Date(lastStamp*1000).toISOString().slice(0,10):'',source:'Yahoo 日K'};return quoteCache[key]}catch(err){continue}}quoteCache[key]={prices:series(100+item.symbol.length*7,1.1),asOf:'',source:'示範線，公開日K抓取失敗'};return quoteCache[key]}
function sma(values,n){if(values.length<n)return null;return values.slice(-n).reduce((a,b)=>a+b,0)/n}
function rsi(values){let gain=0,loss=0;for(let i=values.length-14;i<values.length;i++){const d=values[i]-values[i-1];if(d>=0)gain+=d;else loss-=d}if(loss===0)return 100;const rs=gain/loss;return 100-100/(1+rs)}
function analyze(item,quote){const prices=quote.prices;const last=prices.at(-1);const ma20=sma(prices,20);const ma60=sma(prices,60);const r=rsi(prices);const high20=Math.max(...prices.slice(-20));const reasons=[];let bias='flat';let action=item.kind==='hold'?'續抱觀察':'觀望';if(last>ma20&&ma20>ma60){bias='bull';reasons.push('收盤價在 20 日與 60 日均線之上');action=item.kind==='hold'?'續抱':'突破條件接近，仍等量能'}else if(last<ma20&&ma20<ma60){bias='bear';reasons.push('收盤價在 20 日與 60 日均線之下');action=item.kind==='hold'?'減碼觀察':'目前無優勢'}else reasons.push('均線糾結，趨勢不明');if(r>70)reasons.push('RSI '+r.toFixed(0)+'，短線偏熱');else if(r<30)reasons.push('RSI '+r.toFixed(0)+'，短線偏冷');else reasons.push('RSI '+r.toFixed(0)+'，中性');if(last>=high20*0.995)reasons.push('接近近 20 日高點');return {prices,last,ma20,ma60,bias,action,reasons,invalid:bias==='bull'?'跌回 20 日均線下':'重新站上 20 日均線'}}
function save(){localStorage.setItem('desk-items',JSON.stringify(items))}
function draw(canvasPrices){const w=640,h=220,pad=16;const min=Math.min(...canvasPrices),max=Math.max(...canvasPrices);const pts=canvasPrices.map((p,i)=>{const x=pad+(i/(canvasPrices.length-1))*(w-pad*2);const y=h-pad-((p-min)/(max-min||1))*(h-pad*2);return x+','+y}).join(' ');return `<svg class="chart" viewBox="0 0 ${w} ${h}"><polyline fill="none" stroke="#8fd0a8" stroke-width="2" points="${pts}"/></svg>`}
function renderList(){$('list').innerHTML=items.map((item,i)=>`<button class="item ${i===selected?'active':''}" data-i="${i}"><span>${item.market} ${item.symbol}<br><span class="tag">${item.kind==='hold'?'持股':'觀察'} · ${item.name||''}</span></span><span class="tag">移除</span></button>`).join('');$('list').querySelectorAll('.item').forEach(btn=>{btn.onclick=e=>{const i=Number(btn.dataset.i);if(e.target.classList.contains('tag')&&e.target.textContent==='移除'){items.splice(i,1);selected=0;save();render();return}selected=i;render()}})}
async function render(){renderList();const item=items[selected];if(!item){$('detail').innerHTML="<div class='panel'>清單是空的。</div>";return}$('detail').innerHTML=`<article class='panel card'><h2>${item.market} ${item.symbol}</h2><p class='note'>正在抓公開日K…</p></article>`;const quote=await fetchDaily(item);const a=analyze(item,quote);const biasLabel=a.bias==='bull'?'偏多':a.bias==='bear'?'偏空':'觀望';$('detail').innerHTML=`<article class="panel card"><h2>${item.market} ${item.symbol} ${item.name||''}</h2><div class="bias ${a.bias}">${biasLabel} · ${a.action}</div><p class="note">${quote.source}${quote.asOf?' · '+quote.asOf:''} · 收盤 ${a.last.toFixed(2)} · 20日均線 ${a.ma20.toFixed(2)} · 60日均線 ${a.ma60.toFixed(2)}</p>${draw(a.prices)}<ul>${a.reasons.map(r=>`<li>${r}</li>`).join('')}</ul><p>失效條件：${a.invalid}</p><p class="note">${item.note||'沒有筆記'} · 股數 ${item.shares||0} · 成本 ${item.cost||0} · 研究輔助，不是投資建議。</p></article>`}
$('add').onclick=()=>{const symbol=$('symbol').value.trim().toUpperCase();if(!symbol)return;items.unshift({market:$('market').value,symbol,name:'',kind:$('kind').value,shares:Number($('shares').value||0),cost:Number($('cost').value||0),note:$('note').value.trim()});selected=0;save();render()};
$('reset').onclick=()=>{items=SEED;selected=0;save();render()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install').hidden=false});
$('install').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;$('install').hidden=true};
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();
